---
- name: Ensure ruby-install dependencies are installed.
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - bzip2

- name: Check if ruby-install exists already
  stat:
    path: /usr/local/bin/ruby-install
  register: ruby_install

- import_tasks: setup_ruby-install.yml
  when: ruby_install.stat.exists == False
