---
- name: Get ruby-install
  get_url:
    url: "{{ ruby_install_url }}"
    dest: "{{ ruby_install_dir }}"
    mode: 0755
  register: ruby_zip
  when: ruby_install.stat.exists == False

- name: Unarchive ruby-install zip file
  unarchive:
    src: "{{ item }}"
    dest: "{{ ruby_install_dir }}"
    remote_src: yes
  with_items:
    - "{{ ruby_zip.dest }}"
  when: ruby_zip.dest is defined

- name: Make and install ruby-installer
  make: 
    chdir: "{{ ruby_install_dir }}/ruby-install-{{ ruby_install_version }}"
    target: install

- name: Install Ruby from ruby-installer
  command: ruby-install --system --latest ruby 
